[connections.snowflake]
account = "ZLIPOEE.ZSB82120"
user = "Madhumita"
password = "DeepakMadhumita@07"
role = "SYSADMIN"
warehouse = "COMPUTE_WH"
database = "SMOOTHIES"
schema = "PUBLIC"
client_session_keep_alive = true
